const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
const decision=(code,action='hold',events=[])=>({code,source:'weekly-trend-v1',status:'ready',action,label:action,reason:'current',dataDate:'2026-10-02',events});
const event={date:'2026-10-01',action:'add',label:'加碼',reason:'當時達到2R'};
function load(history=[],fail=false){const writes=[];const queries=[];const module={exports:{}};const client={from(table){assert.equal(table,'user_market_daily_cache');const filters={};let max;const b={select(){return b},eq(k,v){filters[k]=v;return b},order(){return b},limit(n){max=n;return b},then(resolve){queries.push({...filters,max});return Promise.resolve({error:fail==='read'?{message:'read failed'}:null,data:filters.cache_date?history.slice(0,1):history}).then(resolve)},upsert(row){writes.push(row);return Promise.resolve({error:fail?{message:'write failed'}:null})}};return b}};const js=ts.transpileModule(fs.readFileSync(__dirname+'/strategy-journal.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(js,{module,exports:module.exports,Date,Map,Set,Promise,Object,Error});return {client,writes,queries,run:module.exports.mergeAndSaveStrategyJournal,save:module.exports.saveStrategyCacheRowPreservingSignals}}
const payload=signals=>({source:'weekly-trend-v1',generatedAt:'2026-10-02T06:00:00Z',signals});
test('retains historical add events without changing current hold action',async()=>{const x=load([{payload:payload({'2330':decision('2330','add',[event])})}]);const result=await x.run(x.client,'owner',payload({'2330':decision('2330')}));assert.equal(result.signals['2330'].action,'hold');assert.equal(result.signals['2330'].events.length,1);assert.equal(result.journalStatus,'saved');assert(x.queries.every(q=>q.user_id==='owner'));assert.equal(x.queries[0].max,400)});
test('preserves same-day codes outside a current subset and ignores old source',async()=>{const x=load([{payload:payload({'2317':decision('2317')})},{payload:{source:'ifalgo-live',signals:{'2330':decision('2330','add',[event])}}}]);const result=await x.run(x.client,'owner',payload({'2330':decision('2330')}));assert.equal(result.signals['2330'].events.length,0);assert.deepEqual(Object.keys(x.writes[0].payload.signals).sort(),['2317','2330']);assert.equal(x.writes[0].signature,'2317,2330')});
test('deduplicates events and rejects future dates',async()=>{const x=load([{payload:payload({'2330':decision('2330','add',[event,event,{...event,date:'2026-10-03'}])})}]);const result=await x.run(x.client,'owner',payload({'2330':decision('2330','hold',[event])}));assert.equal(result.signals['2330'].events.length,1)});
test('reports save failure and returns only current events',async()=>{const x=load([{payload:payload({'2330':decision('2330','add',[event])})}],true);const result=await x.run(x.client,'owner',payload({'2330':decision('2330')}));assert.equal(result.journalStatus,'unavailable');assert.equal(result.signals['2330'].events.length,0);assert.equal(result.journalError,'write failed')});

test('journals the actual current add decision even without a prebuilt historical event',async()=>{const x=load();const result=await x.run(x.client,'owner',payload({'2330':decision('2330','add')}));assert.equal(result.signals['2330'].events.length,1);assert.equal(result.signals['2330'].events[0].date,'2026-10-02');assert.equal(result.signals['2330'].events[0].action,'add');assert.equal(x.writes[0].payload.signals['2330'].events.length,1)});
test('write failure still exposes current actual decision with unavailable journal metadata',async()=>{const x=load([],true);const result=await x.run(x.client,'owner',payload({'2330':decision('2330','add')}));assert.equal(result.journalStatus,'unavailable');assert.equal(result.signals['2330'].events.length,1);assert.equal(result.signals['2330'].events[0].date,'2026-10-02')});

test('read failure never presents unconfirmed historical events',async()=>{const x=load([{payload:payload({'2330':decision('2330','add',[event])})}],'read');const result=await x.run(x.client,'owner',payload({'2330':decision('2330','exit')}));assert.equal(result.journalStatus,'unavailable');assert.equal(x.writes.length,0);assert.equal(result.signals['2330'].events.length,1);assert.equal(result.signals['2330'].events[0].action,'exit');assert.equal(result.signals['2330'].events[0].date,'2026-10-02')});
